- name : Packer vault setup
  hosts: all
  vars_files: ../secrets/secrets.yaml
  roles:
    - role: common
      USER_PASSWORD_HASH: $6$ZsDJWubQN$U67M1iY2OeSUsk4XE/pLKczdPOJ5KyAHvU0PFJmxB0c5eJmu.t772zGfssblB9IthBMCAtJdorgFlj75s7Xsj1
      PKG:
      - unzip
      - jq

  tasks:

    - name: find the temporary inventory file
      run_once: yes
      find:
        paths:
          - '~/gitlab.iscio.com/siocorp/ansible/inventory'
        patterns:
          - '^packer-provisioner-ansible\d+'
        use_regex: yes
      delegate_to: localhost
      register: packer_inventory
        
    - name: merge the consul inventory with the packer inventory
      run_once: yes
      shell:
        cmd: 'cat consul-inventory.cfg >> {{ packer_inventory["files"][0].path }}'
        chdir: ~/gitlab.iscio.com/siocorp/ansible/inventory/
      delegate_to: localhost

    - name: refresh the inventory file
      run_once: yes
      meta: refresh_inventory

    - name: update password used
      set_fact: ansible_become_pass='{{ vault_password }}'

    - name: install consul
      include_role:
        name: consul
    
    - name: install dnsmasq
      include_role:
        name: dnsmasq

    - name: start the consul service
      become: yes
      systemd:
        name: consul
        state: started

    - name: install vault
      include_role:
        name: vault

    - name: check if consul vault datastore is empty
      run_once: yes
      command: consul kv get vault/
      register: check_result
      ignore_errors: yes

    - name: set up vault when consul vault datastore is empty
      when: check_result.rc == 1
      include_role:
        name: new-vault

    - name: add tls 
      include_role:
        name: vault-tls

    - name: stop consul service
      become: yes
      systemd:
        name: consul
        state: stopped
    
    - name: clear the consul data dir
      become: yes
      command: rm -rf /opt/consul/*
