- name: individualize the consul servers
  hosts: consul_prod:consul_dev
  vars_files: ../secrets/secrets.yaml
  vars:
    COUNT: 3

  tasks:
  - name: remove the consul secrets on the worker
    run_once: yes
    command: rm -rf ~/secrets/consul
    delegate_to: localhost

  - name: Create local secrets directory for consul on the worker
    run_once: yes
    file:
      path: ~/secrets/consul
      state: directory
    delegate_to: localhost

  - name: set become password
    set_fact: ansible_become_pass='{{ consul_password }}'

  - name: create gossip_key
    run_once: true
    command: consul keygen
    register: gossip_key

  - name: add the gossip key to the agent config
    become: yes
    lineinfile:
      search_string: 'encrypt = "'
      path: /etc/consul.d/consul.hcl
      line: encrypt = "{{ gossip_key.stdout }}"

  - name: store the gossip key
    run_once: yes
    copy:
      dest: ~/secrets/consul/consul-key
      content: '{{ gossip_key.stdout }}'
    delegate_to: localhost

  - name: generate consul CA
    run_once: yes
    command:
      chdir: ~/secrets/consul
      cmd: consul tls ca create
    delegate_to: localhost

  - name: generate consul certs
    run_once: yes
    command:
      chdir: ~/secrets/consul
      cmd: consul tls cert create -server -dc Homelab
    with_sequence: count='{{ COUNT }}'
    delegate_to: localhost

  - name: get the index integer from the hostname
    set_fact:
      index: '{{ inventory_hostname | regex_search("\d") }}'

  - name: copy certificate to the servers
    become: yes
    copy:
      src: '{{ item }}'
      dest: /etc/consul.d/
    with_items:
      - "~/secrets/consul/consul-agent-ca.pem"
      - "~/secrets/consul/Homelab-server-consul-{{ index }}.pem"
      - "~/secrets/consul/Homelab-server-consul-{{ index }}-key.pem"

  - name: add the certs to the config file
    become: yes
    blockinfile:
      path: /etc/consul.d/consul.hcl
      state: present
      marker_begin: "BEGIN2"
      marker_end: "END2"
      marker: "# {mark} SECOND ANSIBLE MANAGED BLOCK"
      block: |
        cert_file = "/etc/consul.d/Homelab-server-consul-{{ index }}.pem"
        key_file = "/etc/consul.d/Homelab-server-consul-{{ index }}-key.pem"

  - name: enable ui on the first instance
    become: yes
    when: index == '0'
    lineinfile:
      path: /etc/consul.d/server.hcl
      line: ui = true

  - name: restart the consul service
    become: yes
    systemd:
      name: consul
      state: restarted