CONSUL_VERSION: "1.10.2"
CONSUL_URL: https://releases.hashicorp.com/consul
LAN_NETWORK: 192.168.1.0/24
SERVER: no
SERVER_COUNT: "3"
UI: no
CONSUL_SERVER_LIST: '["192.168.1.248","192.168.1.247","192.168.1.246"]'
DATACENTER: "Homelab"
CLIENT_ADDR: '0.0.0.0'